#!/bin/bash

# Script to copy paste the coding environment template.

PROJECTS_DIR=$(readlink -m ~/Projects)
TEMPLATE_DIR=$(readlink -m ~/codingEnv/Template)


PROJECT_NAME=$1

# Check if that project name already exists.
if [ -e $PROJECTS_DIR/$PROJECT_NAME ]
then
    echo "The project $PROJECT_NAME already exists."
    echo
    exit 1
fi


# Create the project directory.
mkdir $PROJECTS_DIR/$1

# Copy the contents of the template into the project.
cp -r $TEMPLATE_DIR/. $PROJECTS_DIR/$1